backend:
  name: github
  branch: master
  repo: dgrammatiko/psalidi

site_url: https://quirky-haibt-91d945.netlify.com

publish_mode: editorial_workflow

media_folder: src_site/assets/uploads/images

public_folder: /assets/uploads/images

locale: 'gr'

slug:
  encoding: 'unicode'
  clean_accents: true
  sanitize_replacement: '_'

collections: # A list of collections the CMS should be able to edit
  - name: 'eggrafa' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Έγγραφα' # Used in the UI
    label_singular: 'Έγγραφα' # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: 'src_site/eggrafa'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: 'Title', name: 'title', widget: 'string', tagname: 'h1'}
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'layouts/apo-ypiresies.njk',
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'select',
          options: ['apo-ypiresies', 'pros-ypiresies'],
        }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          format: '',
        }
      - {
          label: 'Cover Image',
          name: 'image',
          widget: 'image',
          required: false,
          tagname: '',
        }
      - {
          editorComponents: ['image'],
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Main content goes here.',
        }

  - name: 'drastiriotites' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Δραστηριότητες' # Used in the UI
    label_singular: 'Δραστηριότητα' # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: 'src_site/drastiriotites'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: 'Title', name: 'title', widget: 'string', tagname: 'h1'}
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'layouts/apo-ypiresies.njk',
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'select',
          options: ['apo-ypiresies', 'pros-ypiresies'],
        }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          format: '',
        }
      - {
          label: 'Cover Image',
          name: 'image',
          widget: 'image',
          required: false,
          tagname: '',
        }
      - {
          editorComponents: ['image'],
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Main content goes here.',
        }

  - name: 'dimosieymata' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Δημοσιεύματα' # Used in the UI
    label_singular: 'Δημοσιεύμα' # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: 'src_site/dimosieymata'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: 'Title', name: 'title', widget: 'string', tagname: 'h1'}
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'layouts/apo-ypiresies.njk',
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'select',
          options: ['apo-ypiresies', 'pros-ypiresies'],
        }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          format: '',
        }
      - {
          label: 'Cover Image',
          name: 'image',
          widget: 'image',
          required: false,
          tagname: '',
        }
      - {
          editorComponents: ['image'],
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Main content goes here.',
        }

  - label: 'Globals'
    name: 'globals'
    files:
      - label: 'Site Data'
        name: 'site_data'
        delete: false
        file: 'src/_data/site.json'
        fields:
          - {label: 'Site Name', name: 'name', widget: 'string'}
          - {label: 'Site Url', name: 'url', widget: 'string'}
          - {label: 'Author Name', name: 'authorName', widget: 'string'}
          - {label: 'Author Email Address', name: 'authorEmail', widget: 'string'}
          - {
              label: 'Author Twitter Handle',
              name: 'authorHandle',
              widget: 'string',
              required: false,
            }
          - {label: 'Footer Short Description', name: 'shortDesc', widget: 'string'}
          - {
              label: 'Maximum Posts Per Page',
              name: 'maxPostsPerPage',
              widget: 'number',
              default: 5,
            }
          - {
              label: 'Show Theme Credit',
              name: 'showThemeCredit',
              widget: 'boolean',
              default: true,
            }
          - {
              label: 'Enable Third Party Comments Area',
              name: 'enableThirdPartyComments',
              widget: 'boolean',
              default: false,
            }
          - {
              label: 'Payment Pointer (Web Monetization: https://bit.ly/2kTRI1b)',
              name: 'paymentPointer',
              widget: 'string',
            }
          - {
              label: 'Favicon path (EG: /images/favicon.png)',
              name: 'faviconPath',
              widget: 'string',
            }
      - label: 'Navigation'
        name: 'nav'
        delete: false
        file: 'src_site/_data/navigation.json'
        fields:
          - label: 'Items'
            name: 'items'
            widget: 'list'
            fields:
              - {label: 'Text', name: 'text', widget: 'string'}
              - {label: 'Url', name: 'url', widget: 'string'}
              - {
                  label: 'Is url to external site?',
                  name: 'external',
                  widget: 'boolean',
                  required: false,
                }
      - label: 'Social Icons'
        name: 'socials'
        delete: false
        file: 'src_site/_data/socials.json'
        fields:
          - label: 'Items'
            name: 'items'
            widget: 'object'
            fields:
              - {label: 'Facebook', name: 'facebook', widget: 'string'}
              - {label: 'Instagram', name: 'instagram', widget: 'string'}
              - {label: 'Email', name: 'email', widget: 'string'}
      - label: 'Theme Settings'
        name: 'theme'
        delete: false
        file: 'src_site/_data/tokens.json'
        fields:
          - label: 'Size Scale'
            name: 'size-scale'
            widget: 'object'
            fields:
              - {label: 'Base Size', name: 'base', widget: 'string', default: '1rem'}
              - {label: 'Ratio: 300', name: '300', widget: 'string', default: '0.8rem'}
              - {label: 'Ratio: 500', name: '500', widget: 'string', default: '1.25rem'}
              - {label: 'Ratio: 600', name: '600', widget: 'string', default: '1.56rem'}
              - {label: 'Ratio: 700', name: '700', widget: 'string', default: '1.95rem'}
              - {label: 'Ratio: 800', name: '800', widget: 'string', default: '2.44rem'}
              - {label: 'Ratio: 900', name: '900', widget: 'string', default: '3.05rem'}
              - {label: 'Max Size', name: 'max', widget: 'string', default: '4rem'}
          - label: 'Colors'
            name: 'colors'
            widget: 'object'
            fields:
              - {
                  label: 'Primary',
                  name: 'primary',
                  widget: 'string',
                  default: 'hsl(208, 57%, 21%)',
                }
              - {
                  label: 'Primary Shade (darker)',
                  name: 'primary-shade',
                  widget: 'string',
                  default: 'hsl(208, 56%, 14%)',
                }
              - {
                  label: 'Primary Glare (lighter)',
                  name: 'primary-glare',
                  widget: 'string',
                  default: 'hsl(207, 57%, 31%)',
                }
              - {
                  label: 'Highlight',
                  name: 'highlight',
                  widget: 'string',
                  default: 'hsl(42, 98%, 77%)',
                }
              - {
                  label: 'Light',
                  name: 'light',
                  widget: 'string',
                  default: 'hsl(0, 0%, 100%)',
                }
              - {label: 'Mid', name: 'mid', widget: 'string', default: 'hsl(0, 0%, 80%)'}
              - {
                  label: 'Dark',
                  name: 'dark',
                  widget: 'string',
                  default: 'hsl(0, 0%, 20%)',
                }
              - {
                  label: 'Slate',
                  name: 'slate',
                  widget: 'string',
                  default: 'hsl(0, 0%, 25%)',
                }
          - label: 'Fonts'
            name: 'fonts'
            widget: 'hidden'
            default:
              {
                'base': '"-apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, Helvetica, Arial, sans-serif, ''Apple Color Emoji'', ''Segoe UI Emoji'', ''Segoe UI Symbol''"',
                'serif': '"''Lora'', serif"',
              }
