backend:
  name: git-gateway
  branch: master
  repo: psalidi/site

site_url: https://psalidiamarousiou.gr

publish_mode: editorial_workflow

media_folder: src_site/assets/uploads/images
public_folder: "/assets/uploads/images"

locale: 'gr'

slug:
  encoding: 'unicode'
  clean_accents: true
  sanitize_replacement: '_'

collections: # A list of collections the CMS should be able to edit
  - name: 'eggrafa' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Έγγραφα' # Used in the UI
    label_singular: 'Έγγραφα' # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: 'src_site/eggrafa'
    slug: '{{slug}}'
    summary: '{{title}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: 'Title', name: 'title', widget: 'string', tagname: 'h1'}
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'layouts/eggrafa.njk',
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'hidden',
          default: 'eggrafa',
        }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          format: '',
        }
      - {
          label: 'Cover Image',
          name: 'image',
          widget: 'image',
          required: false,
          tagname: '',
        }
      - {
          label: 'Υπότιτλος',
          name: 'description',
          widget: 'markdown',
          minimal: true,
          hint: 'Main content goes here.',
        }
      - {
          editorComponents: ['image'],
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Main content goes here.',
        }
      - {
          label: 'Attachment',
          name: 'attachment',
          widget: 'file',
          required: false,
        }

  - name: 'drastiriotites' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Δραστηριότητες' # Used in the UI
    label_singular: 'Δραστηριότητα' # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: 'src_site/drastiriotites'
    slug: '{{slug}}'
    summary: '{{title}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: 'Title', name: 'title', widget: 'string', tagname: 'h1'}
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'layouts/drastiriotites.njk',
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'hidden',
          default: 'drastiriotites',
        }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          format: '',
        }
      - {
          label: 'Cover Image',
          name: 'image',
          widget: 'image',
          required: false,
          tagname: '',
        }
      - {
          label: 'Υπότιτλος',
          name: 'description',
          widget: 'markdown',
          minimal: true,
          hint: 'Main content goes here.',
        }
      - {
          editorComponents: ['image'],
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Main content goes here.',
        }
      - {
          label: 'Attachment',
          name: 'attachment',
          widget: 'file',
          required: false,
        }

  - name: 'dimosieymata' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Δημοσιεύματα' # Used in the UI
    label_singular: 'Δημοσιεύμα' # Used in the UI, ie: "New Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: 'src_site/dimosieymata'
    slug: '{{slug}}'
    summary: '{{title}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: 'Title', name: 'title', widget: 'string', tagname: 'h1'}
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'layouts/eggrafa.njk',
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'hidden',
          default: 'dimosieymata',
        }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          format: '',
        }
      - {
          label: 'Cover Image',
          name: 'image',
          widget: 'image',
          required: false,
          tagname: '',
        }
      - {
          label: 'Υπότιτλος',
          name: 'description',
          widget: 'markdown',
          minimal: true,
          hint: 'Main content goes here.',
        }
      - {
          editorComponents: ['image'],
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Main content goes here.',
        }
      - {
          label: 'Attachment',
          name: 'attachment',
          widget: 'file',
          required: false
        }

  - label: 'Globals'
    name: 'globals'
    files:
      - label: 'Site Data'
        name: 'site_data'
        delete: false
        file: 'src_site/_data/site.json'
        fields:
          - {label: 'Site Name', name: 'name', widget: 'string'}
          - {label: 'Site Url', name: 'url', widget: 'string'}
          - {label: 'Author Name', name: 'authorName', widget: 'string'}
          - {label: 'Author Email Address', name: 'authorEmail', widget: 'string'}

      - label: 'Navigation'
        name: 'nav'
        delete: false
        file: 'src_site/_data/navigation.json'
        fields:
          - label: 'Items'
            name: 'items'
            widget: 'list'
            fields:
              - {label: 'Text', name: 'text', widget: 'string'}
              - {label: 'Url', name: 'url', widget: 'string'}
              - {
                  label: 'Is url to external site?',
                  name: 'external',
                  widget: 'boolean',
                  required: false,
                }
      - label: 'Social Icons'
        name: 'socials'
        delete: false
        file: 'src_site/_data/socials.json'
        fields:
          - label: 'Items'
            name: 'items'
            widget: 'object'
            fields:
              - {label: 'Facebook', name: 'facebook', widget: 'string'}
              - {label: 'Instagram', name: 'instagram', widget: 'string'}
              - {label: 'Email', name: 'email', widget: 'string'}
      - label: 'Δ.Σ. Συλλόγου'
        name: 'dss'
        delete: false
        file: 'src_site/_data/dss.json'
        fields:
          - label: 'Μέλη'
            name: 'items'
            widget: 'list'
            fields:
              - {label: 'Ονομα/μο', name: 'name', widget: 'string', required: true }
              - {label: 'Περιγραφή', name: 'desc', widget: 'string', required: true }
              - {label: 'Φωτο', name: 'image', widget: 'image', required: false}
